[phases.setup]
nixPkgs = ["nodejs_20"]
cmds = ["corepack enable && corepack prepare pnpm@9 --activate"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "node dist/index.mjs"
