kind = "web"
previewPath = "/"
title = "StrikerX"
version = "1.0.0"
id = "artifacts/strikerx"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20531

[services.development]
run = "pnpm --filter @workspace/strikerx run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/strikerx", "run", "build" ]
publicDir = "artifacts/strikerx/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20531"
BASE_PATH = "/"
